spring.application.name=Ecommerce
server.port=9090

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_multi_vendor
spring.datasource.username=root
spring.datasource.password=thesahoo
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=schinamaya339@gmail.com
spring.mail.password=ixya mzhg snnc wplz
#for enabling app password security we should enable two step verification
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#Described all about sending main : 04:26:18
